### ISSUE TITLE
Timing Issue when creating Pin

### ISSUE THREAD

**Issue by UweKullmann** [SAmeis/pascalio#3]
Class has a timing issue when creating a pin.
if you try to change direction direct after creating the pin, nothing happens.
Reason:
The Costructor is exporting GPIOPin. The Kernel now need some time, this is the reason why direction file not exists. the result is a timing issue. Setdirection is trying to write into a file which is not existing, yet.
One solution could be a sleep which seems not useful.
Maybe a checkroutine in Cunstructor to check exported folder would be a solution.
KR
 Uwe

**Comment by SAmeis** [comment]
There is now a a check with a customizable delay of 20 ms in unit fpsysfs. Please check fpSysFS.ExportCheckDelay and fpSysFS.CheckExported. Commit: ee3cb68beed62aff17591c7b490a650b4e58340f
