### ISSUE TITLE
new unit (PCA9685) I2C 12 Bit 16 Channel Servodriver

### ISSUE THREAD

**Issue by fliegermichl** [SAmeis/pascalio#9]
Hi,
i am working on a little Robot and so i need to control his servos. Using this Raspberry Pi addon card it is really easy.

[pca9685.pas.gz](https://github.com/SAmeis/pascalio/files/4499138/pca9685.pas.gz)

**Comment by SAmeis** [comment]
Thank you very much for the unit!
I've removed Lazlogger dependency and made the constructor work with any TI2CDevice. Please check out commit dd7e3ee.

**Comment by fliegermichl** [comment]
Hi, dit you forget to "git add pca9685.pas"?

**Comment by SAmeis** [comment]
Indeed I did. Shame on me ;-)

Am 28.04.2020 um 09:56 schrieb Michael Läßig:

**Comment by fliegermichl** [comment]
Thank you. Now it does'nt compile because in file gui-src/fpgpiocomp.pas are 
TGPIOInterruptThread.Execute and TGPIOPollThread.Execute not implemented.
since i does'nt use it i have created them using Ctrl-Shift-C and now it works good.
